# -*- coding: utf-8 -*-
"""UC1_CreditCardDefault.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1aQFNB8eIe6HS430IbSx8LdoMCI7KcFmx
"""

!pip install pycaret

from pycaret.utils import enable_colab
enable_colab()

from pycaret.datasets import get_data
credit_data = get_data('credit')
credit_data.shape

data = credit_data.sample(frac=0.95, random_state=786).reset_index(drop=True)
data_unseen = credit_data.drop(data.index).reset_index(drop=True)

print('Data for Modeling: ' + str(data.shape))
print('Unseen Data For Predictions: ' + str(data_unseen.shape))

from pycaret.classification import *
exp = setup(data = data,target='default',session_id=123)

compare_models()

catboost = create_model('catboost')

catboost_tuned = tune_model('catboost')

print(catboost_tuned)

evaluate_model(catboost_tuned)

predict_model(catboost_tuned)

final_catboost = finalize_model(catboost_tuned)

unseen_predictions = predict_model(final_catboost,data=data_unseen)
unseen_predictions.head()

save_model(final_catboost,'CreditCardDefaultModel')

